version: "3"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  cf-typegen:app:
    desc: Generate Cloudflare Workers type definitions for the app package
    dir: ./app
    sources:
      - .vars.dev
      - wrangler.jsonc
    generates:
      - worker-configuration.d.ts
    cmds:
      - yarn cf-typegen

  build:app:
    desc: Build the app package
    dir: ./app
    deps:
      - cf-typegen:app
    sources:
      - src/**/*
      - exclude: src/**/*.story.ts
      - exclude: src/**/*.story.svelte
      - static/**/*
      - svelte.config.js
      - tsconfig.json
      - vite.config.ts
    generates:
      - .svelte-kit/cloudflare/**/*
    cmds:
      - yarn build

  deploy:app:
    desc: Deploy the app package to Cloudflare Workers
    dir: ./app
    deps:
      - build:app
    cmds:
      - yarn deploy

  cf-typegen:db:
    desc: Generate Cloudflare Workers type definitions for the db package
    dir: ./packages/db
    sources:
      - .vars.dev
      - wrangler.jsonc
    generates:
      - worker-configuration.d.ts
    cmds:
      - yarn cf-typegen

  cf-typegen:feed-reader:
    desc: Generate Cloudflare Workers type definitions for the feed-reader package
    dir: ./workers/feed-reader
    sources:
      - .vars.dev
      - wrangler.jsonc
    generates:
      - worker-configuration.d.ts
    cmds:
      - yarn cf-typegen

  cf-typegen:
    desc: Generate Cloudflare Workers type definitions for all packages
    deps:
      - cf-typegen:app
      - cf-typegen:db
      - cf-typegen:feed-reader

  storybook:
    desc: Launch Storybook
    dir: ./app
    cmds:
      - yarn storybook

  deploy:
    desc: Deploys the entire project
    deps:
      - deploy:app
